import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.locator('body').click();
  await page.goto('https://www.naukri.com/');
  await page.getByRole('link', { name: 'Login', exact: true }).click();
  await page.getByRole('textbox', { name: 'Enter your active Email ID /' }).click();
  await page.getByRole('textbox', { name: 'Enter your active Email ID /' }).fill('raju8velpul@gmail.com');
  await page.getByRole('textbox', { name: 'Enter your password' }).click();
  await page.getByRole('textbox', { name: 'Enter your password' }).fill('raju725822');
  await page.getByRole('button', { name: 'Login', exact: true }).click();
  await page.getByRole('textbox', { name: 'Enter your password' }).click();
  await page.getByRole('textbox', { name: 'Enter your password' }).click();
  await page.getByRole('textbox', { name: 'Enter your password' }).fill('raju7258');
  await page.getByRole('textbox', { name: 'Enter your password' }).press('Enter');
  await page.getByRole('button', { name: 'Login', exact: true }).click();
  await page.getByRole('textbox', { name: 'Enter your password' }).click();
  await page.getByText('Show', { exact: true }).click();
  await page.getByRole('textbox', { name: 'Enter your password' }).click();
  await page.getByRole('textbox', { name: 'Enter your password' }).click();
  await page.getByRole('textbox', { name: 'Enter your password' }).fill('ra');
  await page.getByRole('textbox', { name: 'Enter your password' }).click();
  await page.getByRole('textbox', { name: 'Enter your password' }).fill('Raju@5176');
  await page.getByRole('button', { name: 'Login', exact: true }).click();
  await page.getByRole('textbox', { name: 'Enter your active Email ID /' }).click();
  await page.getByRole('textbox', { name: 'Enter your active Email ID /' }).click();
  await page.getByRole('textbox', { name: 'Enter your active Email ID /' }).click();
  await page.getByRole('textbox', { name: 'Enter your active Email ID /' }).click();
  await page.getByRole('textbox', { name: 'Enter your active Email ID /' }).click();
  await page.getByRole('textbox', { name: 'Enter your active Email ID /' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Enter your active Email ID /' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Enter your active Email ID /' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Enter your active Email ID /' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Enter your active Email ID /' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Enter your active Email ID /' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Enter your active Email ID /' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Enter your active Email ID /' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Enter your active Email ID /' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Enter your active Email ID /' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Enter your active Email ID /' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Enter your active Email ID /' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Enter your active Email ID /' }).fill('raju8velpula@gmail.com');
  await page.getByRole('textbox', { name: 'Enter your password' }).click();
  await page.getByRole('textbox', { name: 'Enter your password' }).fill('raju7258');
  await page.getByRole('button', { name: 'Login', exact: true }).click();
  await page.locator('.crossIcon').click();
  await page.getByRole('link', { name: 'View profile' }).click();
  await page.getByRole('button', { name: 'Update resume' }).click();
  await page.getByRole('emphasis').filter({ hasText: 'editOneTheme' }).click();
  await page.getByRole('button', { name: 'Save' }).click();
  await page.locator('.lightbox.profileEditDrawer.profileUpdatedProLayer > .crossLayer > .icon').click();
  await page.getByText('Profile last updated - Today').click();
});